- homepage/scripts/scripts.js
Set Jarvis to be ondemand to improve home page performance (https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=AEMSites&title=a.com+back+to+100)
Resolves: [MWPW-137853](https://jira.corp.adobe.com/browse/MWPW-137853)
**Test URLs:**
- After: https://puru-MWPW-137853--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> MWPW-137853 Jarvis, set to on-demand

- homepage/scripts/scripts.js
This will help LCP to be loaded faster and make sure the media path gets updated when the page is replaced by personalization.
Related PR: https://github.com/adobecom/milo/pull/1605
**Test URLs:**
- After: https://decorate-area--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> Decorate area for fragment LCP and replacePage on personalization

- homepage/blocks/homepage-brick/homepage-brick.js
The recent analytics update to Milo Core switched from using a file called analytics.js to attributes.js.  Some ad blockers prevent files with the word analytics in the name from being downloaded. analytics.js will be deleted soon, so our reference to the old file needs to be updated.
Config object is also sent in support of the future reverse translation feature.
To test the update, check the sources or network tab.  Before should be downloading libs/martech/analytics.js but the after link should be downloading libs/martech/attributes.js
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/drafts/vgoodrich/fragments/analytics/?martech=off
- After: https://martech21--homepage--adobecom.hlx.page/homepage/drafts/vgoodrich/fragments/analytics/?martech=off
> Analytics 2.1 - Switch to attributes.js and send config

- homepage/blocks/homepage-brick/homepage-brick.js
decorateDefaultLinkAnalytics no longer needs the config object.
**Test URLs:**
- After: https://no-config-to-analytics--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> Stop sending config to decorateDefaultLinkAnalytics

- homepage/blocks/homepage-brick/homepage-brick.js
Some ad blockers prevent files with "analytics" in the name from being used. A previous PR in Milo core moved the needed function to attributes.js but an upcoming PR deletes the analytics.js file.  So we must switch our reference before that happens
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?milolibs=mwpw-136617-analytics-en
- After: https://remove-analytics-js--homepage--adobecom.hlx.live/homepage/index-loggedout?milolibs=mwpw-136617-analytics-en
- Short term after (after this PR but before the Milo PR): https://remove-analytics-js--homepage--adobecom.hlx.live/homepage/index-loggedout
> Switch from analytics.js to attributes.js

- homepage/blocks/homepage-brick/homepage-brick.css
- homepage/blocks/homepage-brick/homepage-brick.js
This ticket adds support for the following XD's: 
- https://xd.adobe.com/view/21d87140-6d36-4e14-a738-b44c34a614a7-748b/ - side by side text links, text links are larger than current
- https://xd.adobe.com/view/2b016cd8-4218-4706-b64c-0e447cbe722f-7e52/ - side by side button links + icon in eyebrow
- https://xd.adobe.com/view/ce561bf1-4433-4c29-8018-b41111b70264-9b05/ - stacked links both button and text links, text links are same size as current
Resolves: [MWPW-139931](https://jira.corp.adobe.com/browse/MWPW-139931)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/drafts/chrlin/mashup-examples?martech=off
- After: https://multi-link--homepage--adobecom.hlx.page/homepage/drafts/chrlin/mashup-examples?martech=off
> Homepage brick updates to support upcoming designs

- homepage/scripts/scripts.js
This is needed for CaaS marquees to run queries against the `homepage` content.
**Test URLs:**
- After: https://<branch>--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> Adding chimeraOrigin to homepage repo (milo consumer)

- homepage/scripts/scripts.js
Resolves: [MWPW-142701](https://jira.corp.adobe.com/browse/MWPW-142701)
**Test URLs:**
- After: https://cookie-update--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
QA note:
I've tested with 'test' cookie in Chrome console at adobe.com, and it seems adding cookie as expected with domain `.adobe.com`
> Update cookie with domain '.adobe.com'

- homepage/scripts/scripts.js
Follow up from #66 
Looks like the window.location.replace(''); from flicker fix code doesn't invalidate the browser cache unlike localhost test.
This should work like reload()
Test URLs:
Before: https://stage--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
After: https://flicker-fix--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> Flicker fix

- tools/sidekick/config.json
Send to CaaS Button missing on homepage sidekick.
This is because it wasn't added to `config.json` like other consumers (e.g. bacom)
```
https://github.com/adobecom/bacom/blob/main/tools/sidekick/config.json#L50
```
Jira Ticket: https://jira.corp.adobe.com/browse/MWPW-143459
> MWPW-143459: Adding send to caas button to homepage sidekick

- head.html
This PR avoids the following style for overriding the body opacity that is used to combat flicker.
https://github.com/adobecom/milo/blob/stage/libs/styles/styles.css#L669
Resolves: [CCH-22855](https://jira.corp.adobe.com/browse/CCH-22855)
> cheat css to avoid Milo to override Homepage

- homepage/blocks/homepage-brick/homepage-brick.js
Detailed Description: Homepage brick removes line breaks from headers
................................
Steps to Reproduce:
1. In a page with the homepage-brick block, add a line break (shift+enter) to the header
2. Preview the page
Expected Results: Line break should be present on page.
................................
Actual Results: Line break is missing.
Resolves: [MWPW-146726](https://jira.corp.adobe.com/browse/MWPW-146726)
**Test URLs:**
- Before: https://preserveheaderhtml--homepage--adobecom.hlx.page/homepage/drafts/jacquim/requested-sandbox?martech=off
- After: https://preserveheaderhtml--homepage--adobecom.hlx.page/homepage/drafts/jacquim/requested-sandbox?martech=off
> MWPW-146726 [HOMEPAGE] Homepage brick removes line breaks from headers

- tools/sidekick/config.json
Floodgate actions are dependent on the project and host data sent from the sidekick to perform some actions (similar to how it is setup in dc, cc, bacom etc.). This was missing in the homepage sidekick setup. Updated config.json with this additional info.
Resolves: [MWPW-146847](https://jira.corp.adobe.com/browse/MWPW-146847)
> MWPW-146847: Add project and host to sidekick config

- homepage/scripts/utils.js
This PR extends the nonprod hostnames check that determines if the milolibs query parameter is allowed.
https://jira.corp.adobe.com/browse/MWPW-150667
**Test URLs:**
- After: https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off&milolibs=darth-vader--milo--robert-bogos
> [MWPW-150667] - milolibs query parameter not working

- homepage/scripts/utils.js
- Fixes the inconsistency of pointing to Milo prod libs even when the url is stage.adobe.com
- Fixes potential vulnerability of accepting special characters in branch name.
Resolves: [MWPW-153744](https://jira.corp.adobe.com/browse/MWPW-153744)
**Test URLs:**
- After: https://stage--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> MWPW-153744: Stage URL to point to Stage libs instead of Prod.

- homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.css
- homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.js
Adds a temporary fix to enable using MEP to update background image for homepage linkpod for Max
Steps to QA:
- navigate to this url: https://maxlinkpod--homepage--adobecom.hlx.page/homepage/fragments/loggedout/personalization/pages/hp-10-14-24-max-mweb?mep=%2Fhomepage%2Ffragments%2Fmep%2Fhp-10-14-max.json--all
- confirm that link pod now has the background image shown in the screenshot above, rather than the original linear gradient background
Resolves: [MWPW-158064](https://jira.corp.adobe.com/browse/MWPW-158064)
**Test URLs:**
- After: https://maxlinkpod--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> MWPW-158064 [MEP] Homepage Linkpod for MAX

- homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.css
- homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.js
To address additional requirements added to the ticket, this updates MAX linkpod background override images and linkpod eyebrow size. 
Steps to QA: check that eyebrow text in these four linkpods below, and the "In the news" pod all have font-size set to var(--type-heading-s-size) and line-height set to var(--type-heading-s-lh). 
The Adobe MAX 2024 linkpod background should max this image:
Resolves: [MWPW-158064](https://jira.corp.adobe.com/browse/MWPW-158064)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/fragments/loggedout/personalization/pages/hp-10-14-24-max-mweb?mep=%2Fhomepage%2Ffragments%2Fmep%2Fhp-10-14-max.json--all&martech=off
- After: https://maxlinkpodnewimages--homepage--adobecom.hlx.page/homepage/fragments/loggedout/personalization/pages/hp-10-14- …
> MWPW-158064 [MEP]Homepage Linkpod for MAX

- homepage/scripts/scripts.js
This PR adds the stageDomainsMap, enabling the conversion of production URLs to their stage equivalents in the stage environment.
More details about this feature can be found in [this discussion](https://github.com/orgs/adobecom/discussions/2880).
Resolves: [MWPW-158447](https://jira.corp.adobe.com/browse/MWPW-158447)
**Test URLs:**
Before: https://main--homepage--adobecom.hlx.page/?martech=off
After: https://mwpw-158447-domains-map--homepage--adobecom.hlx.page/?martech=off
> [MWPW-158447] Added stage domains map

- .github/pull_request_template.md
- README.md
- homepage/scripts/utils.js
- test/scripts/utils.test.js
- tools/sidekick/config.json
Upgrading to `.aem.` from `.hlx.` as per the product requirements and [docs](https://www.aem.live/developer/upgrade).
This is not meant to be a complete PR, just one that starts you off. This should be carefully tested.
1. QA, QA, QA
2. Merge
3. Swap origin on the akamai level to consume `aem.page` and `aem.live` 
4. Once origins are switched, remove any references to `hlx.live` or `hlx.page` from the codebase
All variations should continue working: `(hlx|aem).(page|live)`
Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off
After: https://hlx5--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off
Before: https://main--homepage--adobecom.aem.page/homepage/index-loggedout?martech=off (not working, code from this branch is needed)
After: …
> Migrate Homepage to Helix 5

- tools/sidekick/config.json
It seems that https://github.com/adobecom/homepage/pull/140 hasn't been properly tested before being merged and authorization issues are blocking authors from performing their tasks. This PR reverts the preview and live hosts for the time being, until Authorization issues are further investigated.
**Test URLs:**
- After: https://revert-to-hlx--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
> Update preview/live hosts with .hlx. until authorization issues are solved

- homepage/scripts/scripts.js
* CORS issue is seen when loading fragments on graybox
* Akamai has changed the settings on stage
* _stageDomainsMap_ updated to point to stage
* Unfortunately, this fix can only be validated after merged to stage
Resolves: [MWPW-173197](https://jira.corp.adobe.com/browse/MWPW-173197)
**Test URLs:**
- Before: https://main--homepage--adobecom.aem.live/homepage/index-loggedout?martech=off
- After: https://gb-env--homepage--adobecom.aem.live/homepage/index-loggedout?martech=off
> MWPW-173197: graybox env mapped to stage
