adobecom/homepage

homepage/blocks/homepage-brick/homepage-brick.css
homepage/scripts/scripts.js

Move content root update to main

Move content root update to main

---

homepage/scripts/scripts.js

Locales, geoRouting, and fallbackRouting options added to config.
Slack request: https://adobe-mwp.slack.com/archives/C05J8364J0J/p1695663082648119

Locales, geoRouting, and fallbackRouting options added to config.

---

.github/pull_request_template.md
404.html
homepage/blocks/homepage-brick/homepage-brick.css
homepage/blocks/homepage-brick/homepage-brick.js
homepage/scripts/scripts.js
test/blocks/homepage-brick/homepage-brick.test.js

- Font size for link and news pods were too big.
- Now link destination for click pods visible on hover
- Unit test has 100% coverage 
Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off
After: https://stage--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

2 font fixes and click pod hover fix

---

helix-query.yaml
helix-sitemap.yaml

Set up sitemaps for CC Batch 00A - Homepage
Resolves: [MWPW-134180](https://jira.corp.adobe.com/browse/MWPW-134180)
**Test URLs:**
- After: https://mwpw-134180--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

MWPW-134180

---

.github/pull_request_template.md
404.html
homepage/blocks/homepage-brick/homepage-brick.css
homepage/img/favicons/favicon.webmanifest
homepage/scripts/scripts.js

stage -> main

---

homepage/scripts/scripts.js

* Add your
* Specific
* Features or fixes
**Test URLs:**
- After: https://<branch>--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

Configure Jarvis for homepage

---

homepage/blocks/homepage-brick/homepage-brick.css
homepage/blocks/homepage-brick/homepage-brick.js

fix for modal links in "click pods"
To reproduce, go to the before and after pages. In the first pod with the leopard, click the "Start free trial" button
**Test URLs:**
- Before: https://stage--homepage--adobecom.hlx.live/homepage/drafts/index-loggedout?martech=off
- After: https://mashup--homepage--adobecom.hlx.live/homepage/drafts/index-loggedout?martech=off

Mashup - modal fix and style fixes

---

tools/loc/glaas.html
tools/loc/index.html
tools/loc/translation.css
tools/sidekick/config.json

- Adding html files for localization in homepage
Currently, this change will be on `loc` branch
Resolves: [MWPW-137590](https://jira.corp.adobe.com/browse/MWPW-137590)

MWPW-137590: add loc html

---

homepage/scripts/scripts.js

Resolves: [MWPW-137854](https://jira.corp.adobe.com/browse/MWPW-137854)
**Test URLs:**
- After: https://script-update--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

Updating scripts to try loading fast

---

homepage/blocks/homepage-brick/homepage-brick.css
homepage/blocks/homepage-brick/homepage-brick.js
test/blocks/homepage-link-bar/homepage-link-bar.test.js

Resolves: [MWPW-138388](https://jira.corp.adobe.com/browse/MWPW-138388)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/drafts/seanchoi/modal-test?martech=off
- After: https://ost-fix--homepage--adobecom.hlx.page/drafts/seanchoi/modal-test?martech=off
*QA note: the first brick is for modal test. (I needed it since I removed `decorateAutoBlock()` for modal case)

Ost commerce href fix

---

helix-query.yaml
helix-sitemap.yaml

Updating the Sitemap and Query code.
Resolves: [MWPW-138402](https://jira.corp.adobe.com/browse/MWPW-138402)
**Test URLs:**
- After: https://mwpw-138402--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

MWPW-138402

---

homepage/scripts/scripts.js

Adding prodDomains into CONFIG.

adding prodDomains

---

homepage/scripts/scripts.js

Resolves: [MWPW-138901](https://jira.corp.adobe.com/browse/MWPW-138901)
**Test URLs:**
- After: https://homepage-media--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

[MWPW-138901] Homepage media path update

---

homepage/scripts/scripts.js

https://workfront.slack.com/archives/C03DEHB5NE7/p1701807919965099

helpx and stock added

---

homepage/scripts/scripts.js

https://workfront.slack.com/archives/C03DEHB5NE7/p1702064126005689
Before: 
- https://main--homepage--adobecom.hlx.page/cis_ru/homepage/index-loggedout
- https://main--homepage--adobecom.hlx.page/cis_en/homepage/index-loggedout
After:
- https://cis--homepage--adobecom.hlx.page/cis_ru/homepage/index-loggedout
- https://cis--homepage--adobecom.hlx.page/cis_en/homepage/index-loggedout
Stage links after this get merged:
https://www.stage.adobe.com/cis_ru/
https://www.stage.adobe.com/cis_en/

Adding cis locales.

---

homepage/scripts/scripts.js

This is followup from https://github.com/adobecom/homepage/pull/36
https://workfront.slack.com/archives/C03HAU5SU2E/p1701957161241649?thread_ts=1701888249.751869&cid=C03HAU5SU2E
Before: https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
After: https://decorate-area--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

decorateArea to handle only first image to be eager.

---

homepage/scripts/scripts.js

Resolves: [MWPW-141558](https://jira.corp.adobe.com/browse/MWPW-141558)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.live/ro/homepage/index-loggedout?martech=off
- After: https://ro-ro--homepage--adobecom.hlx.live/ro/homepage/index-loggedout?martech=off

en-RO -> ro-RO

---

homepage/scripts/scripts.js

main <- stage

---

homepage/fragments/loggedout/tests/2024/q1/ret0760/susi-light.js

try new location

---

homepage/scripts/scripts.js

Adding loadLana on script.js
**Test URLs:**
- After: https://lana--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off

Adding loadLana on script.js

---

homepage/scripts/scripts.js

Follow up from #61 after review.
**Test URLs:**
- After: https://cookie-update--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

update cookie logic

---

.github/pull_request_template.md
homepage/mep/readme.md
homepage/scripts/scripts.js

Revert "main <- stage"

---

homepage/scripts/scripts.js
homepage/styles/styles.css

Fixing the flicker issue from:
#C
1)Login from https://www.stage.adobe.com/creativecloud/plans.html
2)Click Adobe Logo
Expected : User lands on AHome page without any flickers
actual: Flicker observed when redirection happens from a.com to aHome.
Video: https://jira.corp.adobe.com/secure/attachment/11575679/Screenshare%20-%202024-02-26%209_50_46%20AM.mp4
Resolves: [MWPW-143060](https://jira.corp.adobe.com/browse/MWPW-143060)
**Test URLs:**
- After: https://flicker-fix--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
Note:
After various test, I found out window.location.replace('') will reload the page without showing the content that being rendered.

Fixing flicker issue for the edge case.

---

homepage/scripts/scripts.js

acomsis_stage
**Test URLs:**
- After: https://acomsis-stage--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

acomsis_stage

---

homepage/scripts/scripts.js

As requested,
**Test URLs:**
- After: https://acomsis--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

stage logic update

---

homepage/scripts/scripts.js

Allows GWP to publish and work on pages like:
```
homepage/fragments/loggedout/tests/2024/q2/ace0860/dc
```
Resolves: [MWPW-143895](https://jira.corp.adobe.com/browse/MWPW-143895)
**Test URLs:**
- After: https://mwpw-143895--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

MWPW-143895

---

homepage/scripts/scripts.js

https://github.com/adobecom/homepage/pull/75
* Add your
* Specific
* Features or fixes
**Test URLs:**
- After: https://<branch>--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

[Release] 75 (#76)

---

head.html
homepage/scripts/scripts.js

This PR adds:
- a validation of the token before checking ims status
- a body hiding until IMS status is verified and body hiding is removed only for logged-out users.
Resolves: [CCH-23349](https://jira.corp.adobe.com/browse/CCH-23349)
**Test URLs:**

CCH-23349/CCH-22855: Add ims/flicker related safegards for ahome

---

homepage/scripts/scripts.js

add NPE safety to IMS body hiding removal.
Resolves: [CCH-22855](https://jira.corp.adobe.com/browse/CCH-22855)
**Test URLs:**

CCH-22855: add more safegard

---

homepage/scripts/scripts.js

* Add your
* Specific
* Features or fixes
**Test URLs:**
- After: https://<branch>--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

Update Redirect URI for en Pages

---

homepage/scripts/scripts.js

Revert "Update Redirect URI for en Pages"

---

homepage/scripts/scripts.js

https://redirect-exceptions--homepage--adobecom.hlx.live/homepage/index-loggedout

Redirect exceptions

---

.github/workflows/graybox-sync-repos.yml

* Enable repo-sync for Graybox for Homepage
Resolves: [MWPW-142006](https://jira.corp.adobe.com/browse/MWPW-142006)

MWPW-142006 - Enable repo-sync for graybox

---

homepage/scripts/scripts.js

Resolves: [MWPW-146536](https://jira.corp.adobe.com/browse/MWPW-146536)
https://workfront.slack.com/archives/C05J8364J0J/p1712894219331899
**Test URLs:**
- After: https://recovery-lana-chimeraorigin--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

[MWPW-146536] Recovering missing code from revert #64

---

.github/workflows/graybox-sync-repos.yml
homepage/scripts/scripts.js

Merge stage to main

---

homepage/scripts/scripts.js

- New Akamai update will remove /media_ rules and QA found out fed nav and footer's images are getting 404 since they are getting loaded after media path altering function. This PR is to detect feds' loads and update their media path.
Resolves: [MWPW-146958](https://jira.corp.adobe.com/browse/MWPW-146958)
https://workfront.slack.com/archives/C05J8364J0J/p1713837998307309?thread_ts=1713558036.129549&cid=C05J8364J0J
**Test URLs:**
- After: https://feds-media-fix--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

MutationObserver added for header and footer to alter media path

---

.github/workflows/fg-sync-repos.yml

Floodgate prep for MAX.
[Floodgate DFD](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=WP4&title=Milo+Floodgate+Architecture) 
Resolves: [MWPW-146847](https://jira.corp.adobe.com/browse/MWPW-146847)

MWPW-146847: Repo Sync Workflow for FG

---

tools/sidekick/config.json

Resolves: [MWPW-146847](https://jira.corp.adobe.com/browse/MWPW-146847)

MWPW-146847: Update sidekick for Floodgate

---

homepage/scripts/scripts.js

**Description**
This PR adds the `stageDomainsMap` to the config allowing links to be environment-aware.
More about this new feature can be found in [here](https://github.com/orgs/adobecom/discussions/2437).
Resolves: [MWPW-151457](https://jira.corp.adobe.com/browse/MWPW-151457)

[MWPW 151457] Added stage domains map to make links environment-aware

---

homepage/scripts/mep/ace0861/homepage-brick/homepage-brick.css
homepage/scripts/mep/ace0861/homepage-brick/homepage-brick.js

Merge in test code for ACE0861
MWPW-143637 [Milo]Component Enhancements for ACE0861 Prioritized Plac…

Stage => Main

---

homepage/scripts/scripts.js

Resolves: [MWPW-155512](https://jira.corp.adobe.com/browse/MWPW-155512)
**Test URLs:**
- After: https://media-fix--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

Don't check IMS to avoid reload in case it is media_

---

.github/workflows/fg-sync-repos.yml
.github/workflows/graybox-sync-repos.yml

* Push sync for graybox and floodgate, skipping sync for excluded files.
Resolves: [MWPW-145389](https://jira.corp.adobe.com/browse/MWPW-145389)
**Example summary:**
- Stage: https://github.com/adobecom/milo/actions/runs/10166322730
- Main: https://github.com/adobecom/milo/actions/runs/10177206196

MWPW-145389 Push sync for graybox and floodgate

---

.github/workflows/fg-sync-repos.yml
.github/workflows/graybox-sync-repos.yml
homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.css
homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.js
homepage/scripts/scripts.js

Merge [MWPW-158064 [MEP] Homepage Linkpod for MAX](https://github.com/adobecom/homepage/pull/112) to main

Stage to Main

---

homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.css

**Test URLs:**
- Before: https://maxtweaks--homepage--adobecom.hlx.page/homepage/drafts/msale/10-14-24-max-index-loggedout?martech=off
- After: https://maxtweaks--homepage--adobecom.hlx.page/homepage/drafts/msale/10-14-24-max-index-loggedout?martech=off

Few more MAX tweaks

---

homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.css

Adds marquee eyebrow fix
Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-158064)
**Test URLs:**
- Before: https://stage--homepage--adobecom.hlx.page/homepage/drafts/msale/10-14-24-max-illustrator-pod-index-loggedout?mep=%2Fhomepage%2Ffragments%2Fmep%2Fhp-10-14-max.json--phone---%2Fhomepage%2Ffragments%2Fmep%2Fhp-9-4-amazon-pay-acrobat-extnsn.json--default&martech=off
- After: https://marqueeupdate--homepage--adobecom.hlx.page/homepage/drafts/msale/10-14-24-max-illustrator-pod-index-loggedout?mep=%2Fhomepage%2Ffragments%2Fmep%2Fhp-10-14-max.json--phone---%2Fhomepage%2Ffragments%2Fmep%2Fhp-9-4-amazon-pay-acrobat-extnsn.json--default&martech=off&martech=off

MAX Fix: marquee eyebrow font

---

homepage/scripts/mep/mwpw-158064/homepage-brick/homepage-brick.css

**Test URLs:**
- After: https://stage--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

Stage => Main: MAX update: Add support for RTL background image for Linkpod (#122)

---

homepage/scripts/scripts.js

Resolves: [MWPW-157347](https://jira.corp.adobe.com/browse/MWPW-157347)
https://workfront.slack.com/archives/C05J8364J0J/p1727887756706129
**Test URLs:**
- After: https://stg-domain-map-update--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

Restoring domains those removed

---

homepage/blocks/homepage-brick/homepage-brick.css

https://github.com/adobecom/homepage/pull/135 into main

MWPW-162769[HOMEPAGE] Updates to homepage-brick CSS (#135)

---

homepage/blocks/homepage-brick/homepage-brick.css

Updates the heading spacing update to be more specific
Resolves: [MWPW-162769](https://jira.corp.adobe.com/browse/MWPW-162769)
**Test URLs:**
- After: https://headingspacing--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

[HOMEPAGE] Updates to homepage-brick CSS - heading spacing

---

tools/sidekick/config.json

[MWPW-166162](https://jira.corp.adobe.com/browse/MWPW-166162)
Before: https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off
After: https://hlx-to-aem--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off

MWPW-166162: hlx to aem on sidekick.

---

homepage/scripts/scripts.js

**Test URLs:**
- Before: https://main--homepage--adobecom.aem.live/homepage/index-loggedout?martech=off
- After: https://MWPW-166127--homepage--adobecom.aem.live/homepage/index-loggedout?martech=off

Adding graybox url onto stageDomainMap

---

homepage/blocks/homepage-brick/homepage-brick.css
homepage/blocks/homepage-brick/homepage-brick.js

Resolves: [MWPW-173428](https://jira.corp.adobe.com/browse/MWPW-173428)
**Test URLs:**
- Before: https://main--homepage--adobecom.aem.live/homepage/drafts/seanchoi/index-loggedout?mep=off&martech=off
- After: https://mwpw-173428--homepage--adobecom.aem.live/homepage/drafts/seanchoi/index-loggedout?mep=off&martech=off

MWPW-173428: Supporting "stack" asset for homepage-brick.
